version: '3'

services:
  # mariadb container
  mariadb:
    image: 'mariadb:10.2'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: hanyang
      MYSQL_USER: hyu
      MYSQL_PASSWORD: hyupw
    ports:
      - '3306:3306'
    volumes:
      - './.mariadb:/var/lib/mysql'
