version: '3'

services:
  database:
    image: 'mysql:5.7'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: hanyang
      MYSQL_USER: hyu
      MYSQL_PASSWORD: hyupw
    ports:
      - '3306:3306'
    volumes:
      - './.database:/var/lib/mysql'
